name: flutter_helper_kit
description: flutter_helper_kit helps to improve less code extensions and widgets.
version: 0.0.1
repository: https://github.com/sachin4kmt/flutter_helper_kit
issue_tracker: https://github.com/sachin4kmt/flutter_helper_kit/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.5 <4.0.0'
#  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - widgets
  - extensions
  - utils